name: CI

on:
  push:
    branches:
      - main

jobs:
  Hello:
    runs-on: Ubuntu-24.04
    steps:
      - name: Greetings
        run: echo "Hello World!"

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v6.1.0
