name: linter.yml
on:
  push:
    branches:
      - "main"

jobs:
  Linter:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v6.1.0
        with:
          version: v1.60
